In [1]:
import numpy as np
import matplotlib.pyplot as plt
from well import Well
from geometry_keeper import GeometryKeeper

In [2]:
xwd = 1.
ywd = 0.
outer_bound = "infinite"
top_bound = "imp"
bottom_bound = "imp"
wtype = "frac"
n_stehf = 10
params = {"nseg": 10, "kx": 1., "ky": 1., "kz": 1., "omega": 1, "lambda": 1, "Fcd":1000, "ref_length":1.,
         "z_ref_length": 1}
real_well = Well(xwd, ywd, outer_bound, top_bound, bottom_bound, wtype, params, n_stehf)
well = real_well.lapl_well

In [3]:
real_well.get_pw(1)

1.2236057886748313

In [4]:
from multifrac import Multifrac

In [5]:
xws = np.array([-3., 0., 3.])
yws = np.array([1., 0., -1.])
nwells = 3
outer_bound = "infinite"
top_bound = "imp"
bottom_bound = "imp"
n_stehf = 10
params = {"nseg": 10, "kx": 1., "ky": 1., "kz": 1., "omega": 1, "lambda": 1, "Fcd":1000, "ref_length":1.,
         "z_ref_length": 1}
mf = Multifrac(nwells, xws, yws, outer_bound, top_bound, bottom_bound, params, n_stehf)

In [7]:
mf.lapl_well.lapl_wells

{'well_0': <lapl_well.LaplWell at 0x61d26d0>,
 'well_1': <lapl_well.LaplWell at 0x61d2710>,
 'well_2': <lapl_well.LaplWell at 0x61d2790>}

In [18]:
N = 2
dx = 1/N
xd = -3
m_xd = xd + dx*np.matrix(np.arange(-N+0.5, N+0.5), dtype=np.float).transpose()*np.matrix(np.ones(2*N, dtype=np.float))
m_xj1 = dx*np.matrix(np.ones(2*N, dtype=np.float)).transpose()*np.matrix(np.arange(-N, N), dtype=np.float)
m_xj2 = dx + m_xj1

In [19]:
m_xd

matrix([[-3.75, -3.75, -3.75, -3.75],
        [-3.25, -3.25, -3.25, -3.25],
        [-2.75, -2.75, -2.75, -2.75],
        [-2.25, -2.25, -2.25, -2.25]])

In [20]:
m_xj1

matrix([[-1. , -0.5,  0. ,  0.5],
        [-1. , -0.5,  0. ,  0.5],
        [-1. , -0.5,  0. ,  0.5],
        [-1. , -0.5,  0. ,  0.5]])

In [21]:
m_xj2

matrix([[-0.5,  0. ,  0.5,  1. ],
        [-0.5,  0. ,  0.5,  1. ],
        [-0.5,  0. ,  0.5,  1. ],
        [-0.5,  0. ,  0.5,  1. ]])

In [22]:
yd = 1
ywd = 0
myd = np.matrix((yd - ywd)*np.ones_like(m_xd))

In [23]:
myd

matrix([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])

In [32]:
init_ary = np.dstack([np.array(m_xd), np.array(myd), np.array(m_xj1), np.array(m_xj2)]).reshape(-1, 4)

In [33]:
abs_ary = np.abs(init_ary)

In [34]:
abs_ary

array([[ 3.75,  1.  ,  1.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  0.  ],
       [ 3.75,  1.  ,  0.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  1.  ],
       [ 3.25,  1.  ,  1.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  0.  ],
       [ 3.25,  1.  ,  0.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  1.  ],
       [ 2.75,  1.  ,  1.  ,  0.5 ],
       [ 2.75,  1.  ,  0.5 ,  0.  ],
       [ 2.75,  1.  ,  0.  ,  0.5 ],
       [ 2.75,  1.  ,  0.5 ,  1.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  1.  ]])

In [35]:
abs_ary_2 = np.vstack([abs_ary, abs_ary])
abs_ary_2

array([[ 3.75,  1.  ,  1.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  0.  ],
       [ 3.75,  1.  ,  0.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  1.  ],
       [ 3.25,  1.  ,  1.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  0.  ],
       [ 3.25,  1.  ,  0.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  1.  ],
       [ 2.75,  1.  ,  1.  ,  0.5 ],
       [ 2.75,  1.  ,  0.5 ,  0.  ],
       [ 2.75,  1.  ,  0.  ,  0.5 ],
       [ 2.75,  1.  ,  0.5 ,  1.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  1.  ],
       [ 3.75,  1.  ,  1.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  0.  ],
       [ 3.75,  1.  ,  0.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  1.  ],
       [ 3.25,  1.  ,  1.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  0.  ],
       [ 3.25,  1.  ,  0.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  1.  ],
       [ 2.75,  1.  ,  1.  ,  0.5 ],
       [ 2.75,  1.  ,  0.5 ,  0.  ],
       [ 2.75,  1.  ,  0.  ,  0.5 ],
 

In [37]:
np.unique(abs_ary_2, axis=0)

array([[ 2.25,  1.  ,  0.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  1.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.75,  1.  ,  0.  ,  0.5 ],
       [ 2.75,  1.  ,  0.5 ,  0.  ],
       [ 2.75,  1.  ,  0.5 ,  1.  ],
       [ 2.75,  1.  ,  1.  ,  0.5 ],
       [ 3.25,  1.  ,  0.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  0.  ],
       [ 3.25,  1.  ,  0.5 ,  1.  ],
       [ 3.25,  1.  ,  1.  ,  0.5 ],
       [ 3.75,  1.  ,  0.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  0.  ],
       [ 3.75,  1.  ,  0.5 ,  1.  ],
       [ 3.75,  1.  ,  1.  ,  0.5 ]])

In [38]:
abs_ary

array([[ 3.75,  1.  ,  1.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  0.  ],
       [ 3.75,  1.  ,  0.  ,  0.5 ],
       [ 3.75,  1.  ,  0.5 ,  1.  ],
       [ 3.25,  1.  ,  1.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  0.  ],
       [ 3.25,  1.  ,  0.  ,  0.5 ],
       [ 3.25,  1.  ,  0.5 ,  1.  ],
       [ 2.75,  1.  ,  1.  ,  0.5 ],
       [ 2.75,  1.  ,  0.5 ,  0.  ],
       [ 2.75,  1.  ,  0.  ,  0.5 ],
       [ 2.75,  1.  ,  0.5 ,  1.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  1.  ]])

In [44]:
np.unique(abs_ary_2, axis=0)[np.argwhere(abs_ary==np.unique(abs_ary_2, axis=0))[:,1]]

array([[ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  1.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  1.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  1.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
       [ 2.25,  1.  ,  0.5 ,  1.  ],
       [ 2.25,  1.  ,  1.  ,  0.5 ],
       [ 2.25,  1.  ,  0.5 ,  0.  ],
 