In [4]:
from lapl_well import LaplWell
from sources import Sources
from matrixizer import *

In [5]:
outer_bound = "inf"
top_bound = "imp"
bottom_bound = "imp"
wtype = "frac"
nseg = 10
nwells = 2
xwds = [0, 0]
ywds = [-1, 1]
x_lengths = 1
xed = None
yed = None
zwds = None
hd = None

In [6]:
lapl_well = LaplWell(outer_bound, top_bound, bottom_bound,
                    wtype, nseg, nwells, xwds, ywds)

In [8]:
xis, xjs, xj1s, yws, yds = make_matrix_for_integration(lapl_well.sources_)

In [9]:
yws

array([[-1., -1., -1., ...,  1.,  1.,  1.],
       [-1., -1., -1., ...,  1.,  1.,  1.],
       [-1., -1., -1., ...,  1.,  1.,  1.],
       ..., 
       [-1., -1., -1., ...,  1.,  1.,  1.],
       [-1., -1., -1., ...,  1.,  1.,  1.],
       [-1., -1., -1., ...,  1.,  1.,  1.]])

In [10]:
yds

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [14]:
np.abs(yds-yws)

array([[ 0.,  0.,  0., ...,  2.,  2.,  2.],
       [ 0.,  0.,  0., ...,  2.,  2.,  2.],
       [ 0.,  0.,  0., ...,  2.,  2.,  2.],
       ..., 
       [ 2.,  2.,  2., ...,  0.,  0.,  0.],
       [ 2.,  2.,  2., ...,  0.,  0.,  0.],
       [ 2.,  2.,  2., ...,  0.,  0.,  0.]])

In [8]:
xjs

array([[-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
         0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
         0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
         0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
         0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
         0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
         0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
         0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.

In [8]:
xj1s[0]

array([-1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9,
       -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,
        0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,
        1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ])

In [11]:
xis - xjs

array([[ 0.05, -0.05, -0.15, ..., -3.65, -3.75, -3.85],
       [ 0.15,  0.05, -0.05, ..., -3.55, -3.65, -3.75],
       [ 0.25,  0.15,  0.05, ..., -3.45, -3.55, -3.65],
       ..., 
       [ 3.75,  3.65,  3.55, ...,  0.05, -0.05, -0.15],
       [ 3.85,  3.75,  3.65, ...,  0.15,  0.05, -0.05],
       [ 3.95,  3.85,  3.75, ...,  0.25,  0.15,  0.05]])